### PR TITLE
Tweak to get mac to use local installation

### PR DESCRIPTION
**Pull request by richfitz**

### CODE REVIEW

**Comment by richfitz** [comment]
screen shot 2018-10-18 at 11 34 09 am

**Comment by richfitz** [comment]
Fixes #29, looks like I messed #16 up

**Comment by dirkschumacher** [comment]
@richfitz thanks. I don't see what the problem with #16 is. Can I merge it?

**Comment by richfitz** [comment]
Yes, this can be merged

In #16, the lines that are edited in this PR are incorrect.

**Comment by dirkschumacher** [comment]
👍

**Pull request merged**
